/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:efe28350-7ce0-4d5a-b85d-c7e6aa25a0ab",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PeCfUE4f9",
    "aws_user_pools_web_client_id": "164irp3q7s3ifuulfrjblqlfgk",
    "oauth": {},
    "aws_content_delivery_bucket": "capstone-group4-amazingbookingapp-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://capstone-group4-amazingbookingapp-dev.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
